### ISSUE TITLE
ConverterConfigurer not found

### ISSUE THREAD

**Issue by dpbinh** [rozidan/modelmapper-spring-boot-starter#1]
class ConverterConfigurer not found in the package which is downloaded from maven repository 
https://mvnrepository.com/artifact/com.github.rozidan/modelmapper-spring-boot-starter/1.0.0

**Comment by rozidan** [comment]
Hi, the ConverterConfigurer is exists in the 1.0.1-snapshot version.
Add the sonatype public repository
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/groups/public" }
    ...
}

**Comment by dpbinh** [comment]
thanks for your helps
